[package]
name = "win64-syscall-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-xxhash = { git = "https://github.com/linxGnu/zero-xxhash" }

[lib]
proc-macro = true